package com.cognizant.entity;
// Generated Jun 29, 2017 11:26:56 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.validator.constraints.NotEmpty;

/**
 * TransactionDetails generated by hbm2java
 */
@Entity
@Table(name = "TRANSACTION_DETAILS", catalog = "Bank_Management")
public class TransactionDetails implements java.io.Serializable {

	private long transactionId;
	//@NotEmpty
	private String transactionDescription;
	
	@Transient
	private Long transactionAmount;
	
	//@NotEmpty
	private String transactionType;
	//private Long accountNumber;
	/*@NotEmpty*/
	@Transient
	private long accountBalance;
	
	private UserDetails userDetails;

	public TransactionDetails() {
	}

	public TransactionDetails(long transactionId) {
		this.transactionId = transactionId;
	}

	public TransactionDetails(long transactionId, String transactionDescription, String transactionType,
			Long accountNumber, Long accountBalance) {
		this.transactionId = transactionId;
		this.transactionDescription = transactionDescription;
		this.transactionType = transactionType;
		//this.accountNumber = accountNumber;
		this.accountBalance = accountBalance;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "TRANSACTION_ID", unique = true, nullable = false)
	public long getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(long transactionId) {
		this.transactionId = transactionId;
	}

	@Column(name = "TRANSACTION_DESCRIPTION", length = 20)
	public String getTransactionDescription() {
		return this.transactionDescription;
	}

	public void setTransactionDescription(String transactionDescription) {
		this.transactionDescription = transactionDescription;
	}

	@Column(name = "TRANSACTION_TYPE", length = 10)
	public String getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(String transactionType) {
		this.transactionType = transactionType;
	}

	/*@Column(name = "ACCOUNT_NUMBER")
	public Long getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(Long accountNumber) {
		this.accountNumber = accountNumber;
	}*/

	@Column(name = "ACCOUNT_BALANCE")
	public Long getAccountBalance() {
		return this.accountBalance;
	}

	public void setAccountBalance(Long accountBalance) {
		this.accountBalance = accountBalance;
	}

	@ManyToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "ACCOUNT_NUMBER", nullable = false)
	public UserDetails getUserDetails() {
		return userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	public Long getTransactionAmount() {
		return transactionAmount;
	}

	public void setTransactionAmount(Long transactionAmount) {
		this.transactionAmount = transactionAmount;
	}

}
