package com.cognizant.entity;
// Generated Jun 29, 2017 11:26:56 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


import org.hibernate.validator.constraints.NotEmpty;

/**
 * UserDetails generated by hbm2java
 */
@Entity
@Table(name = "user_details", catalog = "Bank_Management")
public class UserDetails implements java.io.Serializable {

	@NotNull @Min(16) @Max(16)
	private long accountNumber;
	private String accountType;
	private String accountHolderName;
	private Long accountBalance;

	public UserDetails() {
	}

	public UserDetails(long accountNumber, String accountType) {
		this.accountNumber = accountNumber;
		this.accountType = accountType;
	}

	public UserDetails(long accountNumber, String accountType, String accountHolderName, Long accountBalance) {
		this.accountNumber = accountNumber;
		this.accountType = accountType;
		this.accountHolderName = accountHolderName;
		this.accountBalance = accountBalance;
	}

	@Id

	@Column(name = "ACCOUNT_NUMBER", unique = true, nullable = false)
	public long getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(long accountNumber) {
		this.accountNumber = accountNumber;
	}

	@Column(name = "ACCOUNT_TYPE", nullable = false, length = 20)
	public String getAccountType() {
		return this.accountType;
	}

	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}

	@Column(name = "ACCOUNT_HOLDER_NAME", length = 20)
	public String getAccountHolderName() {
		return this.accountHolderName;
	}

	public void setAccountHolderName(String accountHolderName) {
		this.accountHolderName = accountHolderName;
	}

	@Column(name = "ACCOUNT_BALANCE")
	public Long getAccountBalance() {
		return this.accountBalance;
	}

	public void setAccountBalance(Long accountBalance) {
		this.accountBalance = accountBalance;
	}

}
